In [11]:
import numpy as np
np.bool = bool
np.int = int
np.float = float
np.complex = complex
np.object = object
np.str = str

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, load_sample_image
from sklearn.ensemble import RandomForestClassifier

# Set random seed for reproducibility
np.random.seed(0)


In [26]:
iris = load_iris()
df=pd.DataFrame(iris.data , columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [28]:
len(df)

150

In [18]:
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [31]:
df['is_train']= np.random.uniform(0,1,len(df))<= 0.75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   is_train  
0     False  
1      True  
2      True  
3      True  
4     False

In [47]:
train,test = df[df['is_train']==True],df[df['is_train']==False]
print("number of observations in training data:", len(train))
print("number of observations in test data:", len(test))

number of observations in training data: 112
number of observations in test data: 38


In [49]:
features = df.columns[:5]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'is_train'],
      dtype='object')

In [51]:
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [55]:
clf= RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [56]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2])

In [58]:
clf.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [0.  , 0.98, 0.02],
       [0.  , 0.99, 0.01],
       [0.01, 0.98, 0.01],
       [0.  , 0.98, 0.02],
       [0.  , 0.75, 0.25],
       [0.  , 0.98, 0.02]])

In [60]:
preds = iris.target_names[clf.predict(test[features])]
preds[0:25]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor'],
      dtype='<U10')

In [62]:
test['species'].head()

0     setosa
4     setosa
5     setosa
10    setosa
12    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [64]:
pd.crosstab(test['species'],preds,rownames=['actual species'],colnames=['predicted species'])

predicted species  setosa  versicolor  virginica
actual species                                  
setosa                 14           0          0
versicolor              0          13          0
virginica               0           2          9

In [65]:
preds=iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
preds

ValueError: Number of features of the model must match the input. Model n_features is 5 and input n_features is 4 